// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_attachments_upload_id_ from "./routes/api/attachments/upload/[id].ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_dev_trigger_reminders from "./routes/api/dev/trigger-reminders.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_reports_generate from "./routes/api/reports/generate.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $explore from "./routes/explore.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $mou_id_ from "./routes/mou/[id].tsx";
import * as $mou_id_attachments from "./routes/mou/[id]/attachments.tsx";
import * as $mou_id_edit from "./routes/mou/[id]/edit.tsx";
import * as $mou_id_milestones from "./routes/mou/[id]/milestones.tsx";
import * as $mou_id_parties from "./routes/mou/[id]/parties.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/attachments/upload/[id].ts": $api_attachments_upload_id_,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/dev/trigger-reminders.ts": $api_dev_trigger_reminders,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/reports/generate.ts": $api_reports_generate,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/explore.tsx": $explore,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/mou/[id].tsx": $mou_id_,
    "./routes/mou/[id]/attachments.tsx": $mou_id_attachments,
    "./routes/mou/[id]/edit.tsx": $mou_id_edit,
    "./routes/mou/[id]/milestones.tsx": $mou_id_milestones,
    "./routes/mou/[id]/parties.tsx": $mou_id_parties,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
